### ISSUE TITLE
I am a Mac user,I want to give feedback on a bug

### ISSUE THREAD

**Issue by ghost** [Dukeatron/steam#11]
<img width="326" alt="截屏2023-02-19 14 37 44" src="https://user-images.githubusercontent.com/98528213/219933156-4c7b1e4b-5ae9-4db6-abf5-61f5dc931980.png">
On mac, the games that don't work will have an icon, and I can't display it properly after changing the theme to catppuccin

**Comment by ghost** [comment]
Is there something wrong with that font too?

**Comment by ghost** [comment]
<img width="978" alt="截屏2023-02-19 14 47 08" src="https://user-images.githubusercontent.com/98528213/219933406-867cac5b-2bdc-40bf-8495-a085df91cb6b.png">
When I search, there is no icon in the search box

**Comment by Dukeatron** [comment]
The theme is currently broken, we're finding a way to repair it on all operating systems and devices
