### ISSUE TITLE
Latest update breaks round avatar icons in friends

### ISSUE THREAD

**Issue by nellePoint** [Dukeatron/steam#14]
The latest update steam update has made the Steam Friends icons completely broken.
![Screenshot_20230315_042953](https://user-images.githubusercontent.com/9313366/225282790-bb0b786e-f6ae-4f35-969f-e0b28c0f90fd.jpeg)

Mocha Theme

**Comment by Oman395** [comment]
Known bug, been trying to fix for a while but its spaghetti

**Comment by nellePoint** [comment]
understandable
