### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by Dandraghas** [Dukeatron/steam#22]
after new **steam client beta** update its just blank screen:
![image](https://user-images.githubusercontent.com/91272905/235152446-5722cf87-d39c-4a03-a76e-3dad684850ea.png)

it was happened after `Steam Client Beta - April 27th` update

did there any way to uninstall this theme until it fixed?, i cant find docs to do that.

**Comment by Oman395** [comment]
Happens to me too, usually I just need to restart and that fixes it. If you want to uninstall, just delete the ~/.steam/steam/skins/[cpt theme] folder, which should work.

**Comment by Dandraghas** [comment]
> just delete the ~/.steam/steam/skins/[cpt theme] folder, which should work.

its not working, and after some investigation i found that its not catppuccin issue, i created report on ValveSoftware/steam-for-linux

the only thing i found strange is: `[0428/193415.367178:WARNING:gpu_process_host.cc(1256)] The GPU process has crashed 1 time(s)`

**Comment by Dandraghas** [comment]
im fully reinstalled steam(including deleting local/share/steam) and now everything works.

**Comment by tlneondo** [comment]
Still having this issue, Recreated steam folder from scratch.

Here's the output from tail -f on the logfiles as I switch between library and store page and attempt to resize the window.
[steamtailout.txt](https://github.com/catppuccin/steam/files/11437302/steamtailout.txt)
