### ISSUE TITLE
Not appearing on skins list

### ISSUE THREAD

**Issue by Yama-K** [Dukeatron/steam#24]
I'm on windows 10 currently, none of the themes appear on the skins list in interface settings. Had to install other unrelated skin to see if it would pop up on the list, and to confirm I wasn't screwing up anything.

**Comment by Oman395** [comment]
Could you send a screenshot of your skins folder? It should show up if the  folder is there at all

**Comment by Yama-K** [comment]
Sure
![image](https://github.com/catppuccin/steam/assets/26037681/6ca8e3a5-0a30-4352-ad86-112c85d16e8c)
I don't honestly even know anymore how to change skins due to the recent update on steam
