### ISSUE TITLE
The project is (seemingly) dead, luckily another project takes its spot

### ISSUE THREAD

**Issue by HasuMigu** [Dukeatron/steam#26]
Due to the new Steam Client update, there has been major changes to the interface, breaking almost all older steam skins with no easy way to insert a skin. There is luckily a project named Adwaita-for-Steam which brings the LibAdwaita look to Steam. The project also comes with a variety of colorthemes so you're not forced to use the default Adwaita themes, including Catppuccin's dark mode themes (no latte respect ): )

Adwaita-for-Steam: [https://github.com/tkashkin/Adwaita-for-Steam](https://github.com/tkashkin/Adwaita-for-Steam)

**Comment by popcornman209** [comment]
yup, ive been trying to install it but the manual install neither the auto install works, ill do the one you sent, thanks!

**Comment by Oman395** [comment]
Can confirm it's a bit dead, truth be told I've pretty much just been putting off rewriting it for the new client-- I will have time in the summer to work on it hopefully though, so I might be able to get it done. And as for adwaita-- honestly I just don't like it very much, so I'm going to probably work on my own thing, but I might add a note about it to the readme

**Comment by badlydrawnface** [comment]
Looks very good!!!

![image](https://github.com/catppuccin/steam/assets/53501005/36df74fd-c08b-434d-b8ff-a49ded4d6b45)

**Comment by Covkie** [comment]
[Steam-Library](https://github.com/AikoMidori/steam-library/) has switched to using [SFP](https://github.com/PhantomGamers/SFP) which has support for theming + script injection (for easy flavour and palette picking😊) and is cross platform - though Steam-Library seems to be broken and some areas no longer theme correctly. 


~~I may have some time next weekend so I'll see if I'm able to get something working :3~~



Edit: Full Dark Mode by FatheredPuma81 (Included in [SteamUI-OldGlory](https://github.com/Jonius7/SteamUI-OldGlory)) seems to properly theme a large amount of the steam client. Might be a better place to build from.
