### ISSUE TITLE
Add alternative link + Metro patch to instructions

### ISSUE THREAD

**Issue by eclairevoyant** [Dukeatron/steam#3]
The original Metro skin is also hosted at [minischetti/metro-for-steam](https://github.com/minischetti/metro-for-steam), so that can be an alternate link if the website goes down. Also, the current release (4.4) of metro is broken as is, and the community has created a patch in [redsigma/UPMetroSkin ](https://github.com/redsigma/UPMetroSkin/) to address this. I suggest adding this patch to the install instructions.

**Comment by Dukeatron** [comment]
Implemented

**Comment by eclairevoyant** [comment]
Thanks!
